AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 10
    MemorySize: 5000
  Api:
    BinaryMediaTypes:
      - image/png
      - image/jpg
      - image/jpeg

Resources:
  InferenceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: lambda_function.handler
      Runtime: python3.11
      MemorySize: 5000
      Timeout: 100
      Environment:
        Variables:
          FASTAPI_MODULE: "lambda_function.handler"
      Architectures:
        - x86_64
      Events:
        InferenceApi:
          Type: Api
          Properties:
            Path: /predict
            Method: POST
        TestApi:
          Type: Api
          Properties:
            Path: /test
            Method: GET
      Policies:
        - AWSLambdaBasicExecutionRole
    Metadata:
      BuildMethod: python3.11

Outputs:
  InferenceFunction:
    Description: Inference Lambda Function ARN
    Value: !GetAtt InferenceFunction.Arn
  InferenceFunctionIamRole:
    Description: Implicit IAM Role created for Inference function
    Value: !GetAtt InferenceFunctionRole.Arn
  ApiUrl:
    Description: "API Gateway endpoint URL for the Inference function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
